from django.conf.urls import patterns, url

from .views import (
    IndexView,
    AnimalsListView,
    AnimalAddView,
    AnimalEditView,
    AnimalsListExportXLSView,
    AnimalsStatisticView,
    OwnersListView,
    OwnersFormView,
    KennelsListView,
    KennelsFormView,
    LoginView,
    LogoutView,
    ShowGroupsListView,
    ShowGroupsAddView,
    ShowGroupsEditView,
    ShowGroupsEditCheckInView,
    ShowGroupDeleteView,
    ShowAddView,
    ShowEditView,
    ShowDeleteView,
    ShowMemberCreateView,
    ShowPrintMembersView,
    ShowPrintMembersPDFView,
    ShowPrintCertlistView,
    ShowPrintCertlistPDFView,
    ShowCertlistSetNumbersView,
    ShowMemberDeleteView,
    CatalogListView,
    CatalogAddView,
    CatalogDetailView,
    CatalogAddShowitemlView,
    DocTplListView,
    DocTplAddView,
    DocTplEditView,
    DocTplSelectView,
    DocTplPrintSelectView,
    DocTplPrintPDFView,
    ExportCatalogHTMLView, ExportCatalogPDFView,
    AjaxBreedSearchView,
    AjaxAnimalCreateView,
    AjaxAnimalSearchView,
    AjaxOwnerSearchView,
    AjaxKennelSearchView,
    AjaxAnimalOwnerFormView,
    AjaxAnimalKennelFormView
)


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='core_index'),
    url(r'^list/$', AnimalsListView.as_view(), name='core_animals_list'),
    url(r'^list/ex/$', AnimalsListView.as_view(extended=True), name='core_animals_list_ex'),
    url(r'^add/$', AnimalAddView.as_view(), name='core_animals_add'),
    url(r'^edit/(?P<pk>\d+)/$', AnimalEditView.as_view(), name='core_animals_edit'),
    url(r'^list/export/xls/$', AnimalsListExportXLSView.as_view(), name='core_animals_export_xls'),
    url(r'^statistic/$', AnimalsStatisticView.as_view(), name='core_animals_statistic'),

    url(r'^owners/list/$', OwnersListView.as_view(), name='core_owners_list'),
    url(r'^owners/add/$', OwnersFormView.as_view(), name='core_owner_create'),
    url(r'^owners/edit/(?P<pk>\d+)/$', OwnersFormView.as_view(), name='core_owner_edit'),

    url(r'^kennels/list/$', KennelsListView.as_view(), name='core_kennels_list'),
    url(r'^kennels/add/$', KennelsFormView.as_view(), name='core_kennel_create'),
    url(r'^kennels/edit/(?P<pk>\d+)/$', KennelsFormView.as_view(), name='core_kennel_edit'),

    url(r'^login/$', LoginView.as_view(), name='core_login'),
    url(r'^logout/$', LogoutView.as_view(), name='core_logout'),
    url(r'^show/groups/list/$', ShowGroupsListView.as_view(), name='core_show_groups_list'),
    url(r'^show/groups/add/$', ShowGroupsAddView.as_view(), name='core_show_groups_add'),
    url(r'^show/groups/(?P<pk>\d+)/$', ShowGroupsEditView.as_view(), name='core_show_groups_edit'),
    url(r'^show/groups/(?P<pk>\d+)/check_in/$', ShowGroupsEditCheckInView.as_view(),
        name='core_show_groups_edit_check_in'),
    url(r'^show/groups/(?P<pk>\d+)/check_out/$', ShowGroupsEditCheckInView.as_view(checkin_mode='do_open'),
        name='core_show_groups_edit_check_out'),
    url(r'^show/groups/(?P<pk>\d+)/delete/$', ShowGroupDeleteView.as_view(), name='core_show_group_delete'),
    url(r'^show/groups/(?P<group>\d+)/show/add/$', ShowAddView.as_view(), name='core_show_add'),
    url(r'^show/groups/(?P<group>\d+)/show/(?P<pk>\d+)/$', ShowEditView.as_view(), name='core_show_edit'),
    url(r'^show/groups/(?P<group>\d+)/show/(?P<pk>\d+)/delete/$', ShowDeleteView.as_view(), name='core_show_delete'),
    url(r'^show/groups/(?P<group>\d+)/show/(?P<pk>\d+)/member/add/$', ShowMemberCreateView.as_view(),
        name='core_show_member_add'),
    url(r'^show/groups/(?P<group>\d+)/show/(?P<pk>\d+)/print/members/$', ShowPrintMembersView.as_view(),
        name='core_show_members_print'),
    url(r'^show/groups/(?P<group>\d+)/show/(?P<pk>\d+)/print/members/pdf/$', ShowPrintMembersPDFView.as_view(),
        name='core_show_members_print_pdf'),
    url(r'^show/certlist/group/(?P<pk>\d+)/(?P<title>[^/]+)/print/$', ShowPrintCertlistView.as_view(),
        name='core_show_certlist_print'),
    url(r'^show/certlist/group/(?P<pk>\d+)/(?P<title>[^/]+)/print/pdf/$', ShowPrintCertlistPDFView.as_view(),
        name='core_show_certlist_print_pdf'),
    url(r'^show/certlist/group/(?P<pk>\d+)/(?P<title>[^/]+)/setnumbers/$', ShowCertlistSetNumbersView.as_view(),
        name='core_show_certlist_set_numbers'),
    url(r'^show/member/(?P<pk>\d+)/delete/$', ShowMemberDeleteView.as_view(), name='core_show_member_delete'),
    url(r'^show/catalogs/$', CatalogListView.as_view(), name='core_show_catalogs_list'),
    url(r'^show/catalogs/add/$', CatalogAddView.as_view(), name='core_show_catalogs_add'),
    url(r'^show/catalogs/(?P<pk>\d+)/$', CatalogDetailView.as_view(), name='core_show_catalogs_detail'),
    url(r'^show/catalogs/(?P<pk>\d+)/addshowitem/$', CatalogAddShowitemlView.as_view(),
        name='core_show_catalogs_add_showitem'),
    url(r'^show/(?P<pk>\d+)/export/catalog/html/$', ExportCatalogHTMLView.as_view(), name='core_export_catalog_html'),
    url(r'^show/(?P<pk>\d+)/export/catalog/pdf/$', ExportCatalogPDFView.as_view(), name='core_export_catalog_pdf'),
    url(r'^doctpl/list/$', DocTplListView.as_view(), name='core_doctpl_list'),
    url(r'^doctpl/add/$', DocTplAddView.as_view(), name='core_doctpl_add'),
    url(r'^doctpl/edit/(?P<pk>\d+)/$', DocTplEditView.as_view(), name='core_doctpl_edit'),
    url(r'^doctpl/select/$', DocTplSelectView.as_view(), name='core_doctpl_select'),
    url(r'^doctpl/print/select/$', DocTplPrintSelectView.as_view(), name='core_doctpl_print_select'),
    url(r'^doctpl/print/preview/$', DocTplEditView.as_view(mode='print_preview'), name='core_doctpl_print_preview'),
    url(r'^doctpl/print/done/$', DocTplEditView.as_view(mode='print_done'), name='core_doctpl_print_done'),
    url(r'^doctpl/print/pdf/$', DocTplPrintPDFView.as_view(), name='core_doctpl_print_pdf'),
    url(r'^ajax/breed/search/$', AjaxBreedSearchView.as_view(), name='core_ajax_breed_search'),
    url(r'^ajax/animal/create/$', AjaxAnimalCreateView.as_view(), name='core_ajax_animal_create'),
    url(r'^ajax/animal/search/$', AjaxAnimalSearchView.as_view(), name='core_ajax_animal_search'),
    url(r'^ajax/owner/search/$', AjaxOwnerSearchView.as_view(), name='core_ajax_owner_search'),
    url(r'^ajax/kennel/search/$', AjaxKennelSearchView.as_view(), name='core_ajax_kennel_search'),
    url(r'^ajax/owner/create/$', AjaxAnimalOwnerFormView.as_view(), name='core_ajax_owner_create'),
    url(r'^ajax/kennel/create/$', AjaxAnimalKennelFormView.as_view(), name='core_ajax_kennel_create'),
)


try:
    from django.conf import settings
    if settings.DEBUG:
        urlpatterns += patterns('',
            url(r'^media/(.*)$', 'django.views.static.serve', kwargs={'document_root': settings.MEDIA_ROOT}),
        )
except:
    pass